### ISSUE TITLE
t3d import + actors to object( blender emptys with actor names)

### ISSUE THREAD

**Issue by rubening87** [cmbasnett/io_scene_t3d#1]
Thank you for this.
would be much to suggest the import t3d in the tool?, maybe its possible to add the actors as a blender object wiith the actors name. so when it gets back exported, it will check the objects name, rotation and location and add it inside the exported t3d with the rest of the geometry?.

I could try to do it taking this script but would like to know if you had any issue if you tried.

**Comment by cmbasnett** [comment]
This is honestly probably out of the scope for what I'm willing to do, at this point anyways. It's a dream of mine to be able to essentially make maps within Blender almost entirely, and this would be a part of it. I'm going to close this as it's not on the roadmap.

**Comment by rubening87** [comment]
it was not really clear and confussing what you mean, but i understand you're not interested. thank you anyway. if i ever do it, ill let you know. cheers.

**Comment by rubening87** [comment]
> This is honestly probably out of the scope for what I'm willing to do, at this point anyways. It's a dream of mine to be able to essentially make maps within Blender almost entirely, and this would be a part of it. I'm going to close this as it's not on the roadmap.

i dont get it.. you say "out of the scope"...then you say "this would be part of it" then you say "its not on the road map".. 
i got confused. what do you mean "this would be part of it" what would? the import ? or the blender object to actors? 

you plan to figure out the light in blender to match similar light in unreal editor? that would be awesome.
